//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeRent.Exception.ExceptionBase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ErrorsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BikeRent.Exception.ExceptionBase.ErrorsMessages", typeof(ErrorsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento não pode estar em branco.
        /// </summary>
        public static string BlankBirthDate {
            get {
                return ResourceManager.GetString("BlankBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número da CNH não pode estar em branco.
        /// </summary>
        public static string BlankCNHNumber {
            get {
                return ResourceManager.GetString("BlankCNHNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ não pode estar em branco.
        /// </summary>
        public static string BlankCNPJ {
            get {
                return ResourceManager.GetString("BlankCNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail não pode estar em branco.
        /// </summary>
        public static string BlankEmail {
            get {
                return ResourceManager.GetString("BlankEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome não pode estar em branco.
        /// </summary>
        public static string BlankName {
            get {
                return ResourceManager.GetString("BlankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha não pode estar em branco.
        /// </summary>
        public static string BlankPassword {
            get {
                return ResourceManager.GetString("BlankPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNH já cadastrada.
        /// </summary>
        public static string CNHAlreadyRegistered {
            get {
                return ResourceManager.GetString("CNHAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria da CNH inválida.
        /// </summary>
        public static string CNHCategory {
            get {
                return ResourceManager.GetString("CNHCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ já cadastrado.
        /// </summary>
        public static string CNPJAlreadyRegistered {
            get {
                return ResourceManager.GetString("CNPJAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo CNPJ deve conter apenas números.
        /// </summary>
        public static string CNPJOnlyNumbers {
            get {
                return ResourceManager.GetString("CNPJOnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail já cadastrado.
        /// </summary>
        public static string EmailAlreadyRegistered {
            get {
                return ResourceManager.GetString("EmailAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ informado é inválido.
        /// </summary>
        public static string InvalidCNPJ {
            get {
                return ResourceManager.GetString("InvalidCNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail informado inválido.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail ou senha incorretos.
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha deve conter ao menos seis caractres.
        /// </summary>
        public static string MinimumSixCharacters {
            get {
                return ResourceManager.GetString("MinimumSixCharacters", resourceCulture);
            }
        }
    }
}
